// <auto-generated />
namespace AgendamentoEnergia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Agorasim : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agorasim));
        
        string IMigrationMetadata.Id
        {
            get { return "202201020425542_Agorasim"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
